const poses = {
    idle: [
      "        HhHHhH          ",
      "      HHHhHhHHHHH       ",
      "     HHhSSSSSSShHH      ",
      "     HHSSSSSSSSSSHH     ",
      "     HPEsSSSSSsEPH      ",
      "     HHSSsSsSSSsHH      ",
      "      HsSRRRRSSsH       ",
      "       sSSMMMSSs        ",
      "        sSSSSSs         ",
      "         sSSs           ",
      "       WWWTWWWWW        ",
      "      WWWTTWWWWWW       ",
      "     GWWNAWWWWWWWG      ",
      "    sGWWAAWWWWWWWGs     ",
      "   ssGWWWAWAWWWWWGss    ",
      "   ssGWWWCWWCWWWWGss    ",
      "   ss gWWWWWWWWWg ss    ",
      "   ss  WWWWWWWWW  ss    ",
      "   ss  gWWWWWWWg  ss    ",
      "    s   WWWWWWW   s     ",
      "        BBBBBBB         ",
      "        bBB BBb         ",
      "        bBB BBb         ",
      "        bBB BBb         ",
      "       KkKK KkKK        ",
    ],
    tap: [
      "        HhHHhH          ",
      "      HHHhHhHHHHH       ",
      "     HHhSSSSSSShHH      ",
      "     HHSSSSSSSSSSHH     ",
      "     HPEsSSSSSsEPH      ",
      "     HHSSsSsSSSsHH      ",
      "      HsSRRRRSSsH       ",
      "       sSSMMMSSs        ",
      "        sSSSSSs         ",
      "         sSSs           ",
      "       WWWTWWWWW        ",
      "      WWWTTWWWWWW       ",
      "     GWWNAWWWWWWWG      ",
      "    sGWWAAWWWWWWWGssssss",
      "   ssGWWWAWAWWWWWG sssss",
      "   ssGWWWCWWCWWWWGss    ",
      "   ss gWWWWWWWWWg ss    ",
      "   ss  WWWWWWWWW  s     ",
      "   ss  gWWWWWWWg        ",
      "    s   WWWWWWW         ",
      "        BBBBBBB         ",
      "        bBB BBb         ",
      "        bBB BBb         ",
      "        bBB BBb         ",
      "       KkKK KkKK        ",
    ],
    watch: [
      "        HhHHhH          ",
      "      HHHhHhHHHHH       ",
      "     HHhSSSSSSShHH      ",
      "     HHSSSSSSSSSSHH     ",
      "     HPsSSSSSSEPHH      ",
      "     HHSSsSsSSSsHH      ",
      "      HsSRRRRSSsH       ",
      "       sSSSMSSs         ",
      "        sSSSSSs         ",
      "         sSSs           ",
      "       WWWTWWWWW        ",
      "      WWWTTWWWWWW       ",
      "     GWWNAWWWWWWWG      ",
      "    sGWWAAWWWWWWWGs     ",
      "   ssGWWWAWAWWWWWGss    ",
      "   ssGWWWCWWCWWWWGss    ",
      "   ssgWWWWWWWWWWWgss    ",
      "   ss gWWWWWWWWWg ss    ",
      "   ss  gWWWWWWWg  ss    ",
      "    s   WWWWWWW   s     ",
      "        BBBBBBB         ",
      "        bBB BBb         ",
      "        bBB BBb         ",
      "        bBB BBb         ",
      "       KkKK KkKK        ",
    ],
    worried: [
      "        HhHHhH          ",
      "      HHHhHhHHHHH       ",
      "     HHhSSSSSSShHH      ",
      "     HHSSSSSSSSSSHH     ",
      "     HPEsSSSSSsEPH      ",
      "     HHSSsSsSSSsHH      ",
      "      HsSRRRRSSsH       ",
      "       sSSOMOSSSs       ",
      "       ssSSSSSss        ",
      "       GssSSsSsWG       ",
      "      GWWsTTWsWWWG      ",
      "     GWWWTTTTWWWWWG     ",
      "     GWWNAWWWWWWWG      ",
      "    sGWWAAWWWWWWWGs     ",
      "   ssGWWWAWAWWWWWGss    ",
      "   ssGWWWCWWCWWWWGss    ",
      "   ssgWWWWWWWWWWWgss    ",
      "   ssgWWWWWWWWWWWgss    ",
      "   ss  gWWWWWWWg  ss    ",
      "    s   WWWWWWW   s     ",
      "        BBBBBBB         ",
      "        bBB BBb         ",
      "        bBB BBb         ",
      "        bBB BBb         ",
      "       KkKK KkKK        ",
    ],
    celebrate: [
      "        HhHHhH          ",
      "      HHHhHhHHHHH       ",
      "     HHhSSSSSSShHH      ",
      "     HHSSSSSSSSSSHH     ",
      "     HPEsSSSSSsEPH      ",
      "     HHSSsSsSSSsHH      ",
      "      HsSRRRRSSsH       ",
      "       sSSSMSSSs        ",
      "        sSSSSSs         ",
      "         sSSs           ",
      " s     WWWTWWWWW     s  ",
      " ss   WWWTTWWWWWW   ss  ",
      "  ss GWWNAWWWWWWWG ss   ",
      "  ss sGWWAAWWWWWGs ss   ",
      "   sssGWWWAWAWWWGsss    ",
      "      GWWWCWWCWWWG      ",
      "       gWWWWWWWWWg      ",
      "        WWWWWWWWW       ",
      "       gWWWWWWWg        ",
      "        WWWWWWW         ",
      "        BBBBBBB         ",
      "        bBB BBb         ",
      "        bBB BBb         ",
      "        bBB BBb         ",
      "       KkKK KkKK        ",
    ],
};

let allOk = true;
for (const [name, p] of Object.entries(poses)) {
    console.log(`\nPOSE: ${name} (Height: ${p.length})`);
    p.forEach((row, i) => {
        if (row.length !== 24) {
            console.error(`Row ${i} in ${name} has length ${row.length}! "${row}"`);
            allOk = false;
        }
        // print with borders to see outline visually
        console.log(`|${row}|`);
    });
}
if (allOk) console.log("\nALL ROWS HAVE EXACTLY 24 LENGTH!");
